name: expense_manager_app
description: A Flutter app for managing expenses with Firebase integration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Local Database
  sqflite: ^2.3.3
  path: ^1.9.0

  # Firebase Core
  firebase_core: ^4.3.0

  # Cloud Firestore
  cloud_firestore: ^6.1.0

  # Firebase Realtime Database
  firebase_database: ^12.1.0

  # Firebase Authentication
  firebase_auth: ^6.1.3

  # Flutter UI + utilities
  cupertino_icons: ^1.0.5
  provider: ^6.0.7
  intl: ^0.18.1

  # Geolocation
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
