// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKP6mDwGnC_dcdhw-zvTRmlY6IgVnJXfI',
    appId: '1:993006774936:android:3909f5e9c30fdad4d53eed',
    messagingSenderId: '993006774936',
    projectId: 'expense-manager-app-7112c',
    databaseURL: 'https://expense-manager-app-7112c-default-rtdb.firebaseio.com',
    storageBucket: 'expense-manager-app-7112c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-h1alWQj-DQ8XzmYbjmMDKDV3aInYvmE',
    appId: '1:993006774936:ios:5d5907a0c4044a8ad53eed',
    messagingSenderId: '993006774936',
    projectId: 'expense-manager-app-7112c',
    databaseURL: 'https://expense-manager-app-7112c-default-rtdb.firebaseio.com',
    storageBucket: 'expense-manager-app-7112c.firebasestorage.app',
    iosBundleId: 'com.example.expanseManagerApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD27Xyx7VlP41qAeqEeTThsIO46xPmNpKY',
    appId: '1:993006774936:web:b2b7320e0940f4b9d53eed',
    messagingSenderId: '993006774936',
    projectId: 'expense-manager-app-7112c',
    authDomain: 'expense-manager-app-7112c.firebaseapp.com',
    databaseURL: 'https://expense-manager-app-7112c-default-rtdb.firebaseio.com',
    storageBucket: 'expense-manager-app-7112c.firebasestorage.app',
    measurementId: 'G-XRGQK97643',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-h1alWQj-DQ8XzmYbjmMDKDV3aInYvmE',
    appId: '1:993006774936:ios:2c9de685d15747e3d53eed',
    messagingSenderId: '993006774936',
    projectId: 'expense-manager-app-7112c',
    databaseURL: 'https://expense-manager-app-7112c-default-rtdb.firebaseio.com',
    storageBucket: 'expense-manager-app-7112c.firebasestorage.app',
    iosBundleId: 'com.example.expenseManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD27Xyx7VlP41qAeqEeTThsIO46xPmNpKY',
    appId: '1:993006774936:web:0530f703a388dd72d53eed',
    messagingSenderId: '993006774936',
    projectId: 'expense-manager-app-7112c',
    authDomain: 'expense-manager-app-7112c.firebaseapp.com',
    databaseURL: 'https://expense-manager-app-7112c-default-rtdb.firebaseio.com',
    storageBucket: 'expense-manager-app-7112c.firebasestorage.app',
    measurementId: 'G-R3R9N0XVZ8',
  );

}